name: 'nyc_restaurant_grades'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  nyc_restaurant_grades:
    marts:
      +materialized: table
    staging:
      +materialized: view

require-dbt-version: ">=1.0.0"